import{a as P,S as H,i as d}from"./assets/vendor-C1DvvBV_.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function r(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(e){if(e.ep)return;e.ep=!0;const n=r(e);fetch(e.href,n)}})();const M="57834009-e331d273ed5c63387cc2a8569",h=15;async function m(t,o){return await P("https://pixabay.com/api/",{params:{key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:h,page:o}}).then(({data:r})=>r)}const v=new H(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),s={form:document.querySelector(".form"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more")};function g(t){const o=t.map(({webformatURL:r,largeImageURL:i,tags:e,likes:n,views:u,comments:L,downloads:b})=>`
        <li class="gallery-item">
            <a class="gallery-item-link" href="${i}"><img src="${r}" alt="${e}"></a>
            <ul class="gallery-img-info">
              <li class="gallery-info-item">Likes <span>${n}</span></li>
              <li class="gallery-info-item">Views <span>${u}</span></li>
              <li class="gallery-info-item">Comments <span>${L}</span></li>
              <li class="gallery-info-item">Downloads <span>${b}</span></li>
            </ul>
        </li>
        `).join("");v.refresh(),s.gallery.insertAdjacentHTML("beforeend",o)}function S(){s.gallery.innerHTML=""}function y(){s.loader.classList.add("show")}function p(){s.loader.classList.remove("show")}function w(){s.loadMoreBtn.classList.add("is-shown")}function f(){s.loadMoreBtn.classList.remove("is-shown")}s.form.addEventListener("submit",B);s.loadMoreBtn.addEventListener("click",$);let l=1,a="";async function B(t){t.preventDefault(),a=t.currentTarget.elements["search-text"].value.trim(),a&&(f(),S(),y(),l=1,await m(a,l).then(({hits:o,totalHits:r})=>{const i=Math.ceil(r/h);o.length>0?(g(o),w(),l===i&&(c("We're sorry, but you've reached the end of search results.","info"),f())):c(`Sorry, there are no images matching your ${a}. Please try again!`,"error")}).catch(o=>c(o,"error")).finally(()=>p()))}async function $(){a!==""&&(l+=1,y(),await m(a,l).then(({hits:t,totalHits:o})=>{const r=Math.ceil(o/h);if(t.length>0){g(t),w(),console.log("window.scrollY before:",window.scrollY),console.log("doc scrollHeight:",document.documentElement.scrollHeight),console.log("win innerHeight:",window.innerHeight),console.log("max scroll:",document.documentElement.scrollHeight-window.innerHeight);const i=document.querySelector(".gallery-item").getBoundingClientRect().height;console.log("cardHeight:",i),window.scrollBy({top:i*2,behavior:"smooth"}),setTimeout(()=>{console.log("window.scrollY after:",window.scrollY)},700),l===r&&(c("We're sorry, but you've reached the end of search results.","info"),f())}else c(`Sorry, there are no images matching your ${a}. Please try again!`,"error")}).catch(t=>c(t,"error")).finally(()=>p()))}function c(t,o="success"){const r={message:t,position:"topRight",timeout:5e3};switch(o){case"success":d.success(r);break;case"error":d.error(r);break;case"warning":d.warning(r);break;case"info":d.info(r);break;default:d.error({message:"Invalid Type Of toast",position:"topRight",timeout:5e3})}}
//# sourceMappingURL=index.js.map
